#!/bin/bash
set -euo pipefail

# retrieve an existing password
if [ ${#} -eq 0 ]; then
  while read -p "search for: " line; do
    if [ $(( "$(date +%s)" - ${last_success:-0} )) -gt 43200 ]; then
      read -p "passphrase: " -s passphrase
      echo
    fi
    p=$(ssh -q -t mail <<EOF
#!/bin/bash
set -euo pipefail
cd Passwords
gpg --batch -q -o- --passphrase "${passphrase}" validate.asc >/dev/null || exit 1
file=\$(grep -E "Comment: .*${line}" *.asc | sort | tee /dev/stderr | cut -f1 -d':' | tail -1) || exit 0
cred=\$(gpg --batch -q --no-tty --passphrase "${passphrase}" -o - \${file})
echo "\${cred}" | cut -f1 -d'|' > /dev/stderr
echo -n \${cred} | cut -f2 -d'|'
EOF
    )
    echo "$p" | xclip -loops 3 -i -selection clipboard -f | xclip -i -selection primary && last_success=$(date +%s)
  done

# add a new password
elif [ "${1}" == "-a" ]; then

  demo=""
  which apg 2>&1 >/dev/null && demo=" (eg: $(apg -n1 -m 32 -x 64))"

  [ -v username ]   || read -p "username: " username
  [ -v password ]   || read -p "password${demo}: " password
  [ -v private ]    || read -p "additional info to be encrypted: " private
  [ -v keywords ]   || read -p "searchable keywords: " keywords
  [ -v passphrase ] || read -p "passphrase: " -s passphrase

  ssh -q -t mail <<EOF
#!/bin/bash
set -euo pipefail
cd Passwords
gpg --batch -q -o- --passphrase "${passphrase}" >/dev/null validate.asc
num=\$(ls -1 *[0-9]* | sort | tail -1 | grep -oE '[0-9]+')
let num++
file="file\$(printf "%03d" \${num}).asc"
if [ ! -f "\${file}" ]; then
  echo "writing: \${file}"
  echo "$username | $password | $private" \
    | gpg --batch -q --no-tty -c --passphrase '${passphrase}' --cipher-algo AES256 -a --comment '${keywords}' -o \${file}
fi
EOF

fi
