#!/usr/bin/env python
import sys
import os
import glob


ret = 1
for n in glob.iglob('**', recursive=True):
    if not os.path.isdir(n):
        with open(n, 'r', encoding="utf8", errors='ignore') as f:
            lines = f.read()

        linesafter = lines.replace(sys.argv[1], sys.argv[2])

        if lines != linesafter:
            print(n)
            with open(n, 'w') as f:
                f.write(linesafter)
            ret = 0
sys.exit(ret)
