#!/bin/bash
set -uxo pipefail

trap 'echo "killing sshuttle"; killall sshuttle; exit 0' SIGHUP SIGINT SIGQUIT SIGTERM
while true; do
  pkill sshuttle
  sleep 2
  sshuttle -e "ssh -o BatchMode=yes -i /home/alla/.ssh/id_ed25519" --dns -x 104.156.233.200/32 -r alla@45.32.53.181:443 0/0
done
